### ISSUE TITLE
Checklist #1

### ISSUE THREAD

**Issue by Gregorooooo02** [Gregorooooo02/TPW#3]
- [x] text is in C#
- [x] build succeeded
- [x] all UT are green
- [x] `Data` layer is clearly stated using language terms only (no database, no file)
- [x] `Data` API is clearly stated
- [x] `Data` API is abstract
- [x] `Logic` layer is clearly stated using language terms only
- [x] `Logic` API is clearly stated
- [x] `Logic` uses only the abstract `Data` layer API
- [x] `Presentation` layer is clearly stated using language terms only
- [x] `Presentation` uses only the abstract `Logic` layer API
- [x] MVVM and XAMLare applied to implement GUI
- [x] reactive and interactive user interaction for user (operator) communication
- [x] reactive and interactive programming is used for the communication of layers 
- [x] `Presentation` - object model representing process data
- [x] Fulfill functional requirements of the task
- [x] Unit Test - layers are tested independently using abstract API
- [x] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purposes (expected but not required)
